# Generated by Django 6.0.5 on 2026-05-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendorid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('gst_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=9)),
                ('document_path', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'vendor',
                'managed': False,
            },
        ),
    ]
