# Generated by Django 6.0.5 on 2026-06-08 12:08

import back.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('activityid', models.CharField(default=back.helpers.generate_custom_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('action', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'activity_logs',
                'managed': False,
            },
        ),
    ]
