# Generated by Django 6.0.5 on 2026-05-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'notification',
                'managed': False,
            },
        ),
    ]
