# Generated by Django 6.0.5 on 2026-06-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('leadid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('source', models.CharField(choices=[('web', 'Web'), ('referral', 'Referral'), ('social', 'Social'), ('cold_call', 'Cold Call'), ('other', 'Other')], max_length=255)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('negotiating', 'Negotiating'), ('closed', 'Closed'), ('lost', 'Lost')], max_length=15)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lead',
                'managed': False,
            },
        ),
    ]
