# Generated by Django 6.0.5 on 2026-06-02 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('orderid', models.OneToOneField(db_column='orderid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='orders.order')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
            ],
            options={
                'db_table': 'feedback',
                'managed': False,
            },
        ),
    ]
