# Generated by Django 6.0.5 on 2026-06-05 11:08

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('reference_no', models.CharField(default=orders.models.get_default_order_id, max_length=100, primary_key=True, serialize=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('online', 'Online'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('neft', 'NEFT')], max_length=15)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payments',
                'managed': False,
            },
        ),
    ]
